### ISSUE TITLE
bulkrename

### ISSUE THREAD

**Issue by JarrodCTaylor** [francoiscabrol/ranger.vim#15]
I seem to be unable to perform a bulkrename. After selecting the desired files and `:bulkrename %s` the files are opened in regular buffers. Is it possible to perform this from within Vim -> Ranger?

**Comment by francoiscabrol** [comment]
Sorry I give an answer very late but I have checked what Bulkrename do and I don't think this is possible to allow it when you open Ranger from vim/neovim... sorry. Because it is not possible to open vim in vim... you can open neovim in neovim but I think it is not sane to encourage this :/

**Comment by matthewgrossman** [comment]
I use [neovim-remote](https://github.com/mhinz/neovim-remote) to help ensure I don't accidentally [nest](https://github.com/mhinz/neovim-remote#typical-use-cases) an instance of neovim. I do this by ensuring that my `$VISUAL` is `nvr` inside of all `:terminal` buffers.

Has anyone tried of had success getting bulkrename working in that context?
