### ISSUE TITLE
Add support of custom command to open ranger

### ISSUE THREAD

**Issue by srghma** [francoiscabrol/ranger.vim#19]
I want to modify command, that open ranger to open it with custom SHELL (to load .zshrc before ranger for aliases) and custom theme (because default theme look ugly in my vim) like this
`SHELL=/home/bjorn/.config/ranger/rshell ranger --cmd "set colorscheme snow"`

**Comment by BjornMelgaard** [comment]
Had switched to https://github.com/bramblex/ranger.vim/blob/master/plugin/ranger.vim
