### ISSUE TITLE
After loosing focus, ranger is just a text buffer

### ISSUE THREAD

**Issue by BonarBeavis** [francoiscabrol/ranger.vim#22]
Hi,

after loosing focus, ranger is just a text buffer. Can you reproduce this?

NVIM v0.2.0-dev

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

**Comment by francoiscabrol** [comment]
Hi,

Yes I know this behaviour but I think we can't prevent it with neovim. Actually, you just switched to an other vim mode. If you press "i", you will come back to the insert mode of the terminal buffer and you will get the focus back.

**Comment by francoiscabrol** [comment]
This is the way that the neovim terminal buffer works... I don't know any workaround.

**Comment by BonarBeavis** [comment]
Doh, the terminal buffer is in normal mode. Sorry, my bad.
