### ISSUE TITLE
the last commit :  902bb5c  break RangerWorkingDirectoryNewTab

### ISSUE THREAD

**Issue by tofulm** [francoiscabrol/ranger.vim#26]
hi, the[ last commit ](https://github.com/francoiscabrol/ranger.vim/commit/902bb5cafca62695c345513c4adf422807f0d4a0) break : RangerWorkingDirectoryNewTab
with : 
- neovim 0.2
- ranger 1.8

**Comment by francoiscabrol** [comment]
Thanks for the error report! It should be fixed now.

**Comment by tofulm** [comment]
It's ok, Thanks
