### ISSUE TITLE
Turns of relative line numbers if a file is opened from ranger

### ISSUE THREAD

**Issue by snowiow** [francoiscabrol/ranger.vim#29]
I have to `:set rnu` every time I opened a file from ranger. Any idea why?
Thanks in advance :)

**Comment by francoiscabrol** [comment]
I tried and I have the same behaviour but I don't why...

**Comment by snowiow** [comment]
Yes me too. I tried a couple of different scenarios, but it doesn't make any sense. For example: if I start ranger from cli and open a text file with vim, rnu is set...

**Comment by francoiscabrol** [comment]
Do you have still this issue?

**Comment by snowiow** [comment]
yes, currently I have set a shortcut for :set rnu. But that's not the most optimal way :/

**Comment by rhiroyuki** [comment]
I'm currently having the same problem.

**Comment by lazopm** [comment]
same issue here

**Comment by thornycrackers** [comment]
Also the same issue.

**Comment by francoiscabrol** [comment]
I cannot reproduce it anymore with the last versions of neovim and this plugin... is it fixed for you also?

**Comment by francoiscabrol** [comment]
I have just tried with vim8 also and I cannot reproduce anymore
