### ISSUE TITLE
Add option to select different temp file location rather than `/tmp/chosenfile`

### ISSUE THREAD

**Issue by kutsan** [francoiscabrol/ranger.vim#31]
In some systems like Android, users don't have permission to access `/tmp` directory. So, an option to change that would be good. Even better, determinate that if `/tmp` isn't readable prefer `~/.local/ranger.vim/chosenfile ` or `~/.cache/ranger.vim/chosenfile ` as workaround.

**Comment by francoiscabrol** [comment]
Yes that's a reasonable feature request. I will add an option soon (I was busy sorry)

**Comment by kutsan** [comment]
Thanks!

**Comment by kutsan** [comment]
@francoiscabrol Are you aware of `tempname()` function in vim, which handles every edge cases. I think you should use that. Although I don't use this plugin anymore, this is just a friendly advice.
