### ISSUE TITLE
Replace netrw 

### ISSUE THREAD

**Issue by julianwachholz** [francoiscabrol/ranger.vim#33]
Would be nice to be able to disable netrw and have ranger handle opening directories.

**Comment by francoiscabrol** [comment]
Sorry I don't know what netrw do but why is it incompatible with ranger.vim?

**Comment by julianwachholz** [comment]
netrw is the default file browser built into vim. one can disable it an instead have ranger.vim open automatically if you open a directory with vim.

**Comment by code-andres** [comment]
I created a pull request for this issue #36

**Comment by francoiscabrol** [comment]
Merged
