### ISSUE TITLE
kills non ranger buffer

### ISSUE THREAD

**Issue by plexigras** [francoiscabrol/ranger.vim#34]
when i run `:bd` in the ranger term buffer it closes the ranger buffer and then it runs `:bd` again on another buffer

https://github.com/francoiscabrol/ranger.vim/blob/master/plugin/ranger.vim#L31

**Comment by francoiscabrol** [comment]
you should quit ranger by pressing `q`. Does it solve your problem?

**Comment by plexigras** [comment]
`q` works but `:bd` doesnt

**Comment by francoiscabrol** [comment]
I guess we could fix the problem with `:bd` by checking in the `rangerCallback.on_exit` function if the buffer if already closed and not executing `silent! Bclose!` in this case

**Comment by plexigras** [comment]
yeah that would be great

i don't know much vimscript but maybe the exitcodes could be used.

**Comment by francoiscabrol** [comment]
yes the exit code will be 1 instead of 0
