### ISSUE TITLE
Ranger open parent directory instead the current directory

### ISSUE THREAD

**Issue by code-andres** [francoiscabrol/ranger.vim#40]
With the new argument for ranger "--selectfile" when I try open current directory it opens the parent directory. 

For example this is the current directory:
![current_dir](https://user-images.githubusercontent.com/8119013/33175615-b2aa7960-d032-11e7-803f-6232661d40ba.png)

When I open ranger.vim with the current directory command it opens the parent dir.
![parent_dir](https://user-images.githubusercontent.com/8119013/33176510-a5e0fbac-d035-11e7-93ea-d94e6016ddfc.png)

I have a fix for this on NVIM but I need to know if I'm not the only one with the problem to make a PR.

NVIM 0.2.0 - Custom Release Build
ranger-stable 1.8.1

**Comment by francoiscabrol** [comment]
Yes I can reproduce the problem. Me I use to open the current file (RangerCurrentFile) that open the current repository and select the current file.
In the case of RangerCurrentDirectory, the current directory is selected and so the focus is done on the directory itself and not inside the directory.
So I guess when you run RangerCurrentDirectory what you expect is ranger selecting the first file of the current directory and this would be the good behaviour I agree.
If you have an easy fix for that it would be great.

**Comment by code-andres** [comment]
The fix is a small condition checking if the path is a directory and open on that dir... if is a file ranger.vim will open the directory with the file selected this way ranger keep both functions.

I will apply the same condition to VIM and make the PR.

**Comment by francoiscabrol** [comment]
#41 fixed the problem with neovim, thank you @code-andres . Probably the same thing happen with vim, so I will have to check before closing the issue.
