### ISSUE TITLE
How can I use it in fish shell?

### ISSUE THREAD

**Issue by Wheele9** [francoiscabrol/ranger.vim#42]
After pressing leader+F, ranger opens nicely, moving between folders works nicely, but opening the file failes:
My output below powershell:
```
 TERMINAL  term://.//8234:ranger --choosefiles=/tmp/chosenfile --selectfile=""[-]                              [unix]  100% ☰   56/56 ㏑ :  1 
Error detected while processing function 10:                                                                                                  
line    4:                                                                                                                                    
E492: Not an editor command: ^[[36mfish config loaded^@                                                                                                           
Press ENTER or type command to continue         
```                                                

^[[36m... is my welcome message in the shell, shell displays it when I open a new terminal, or when in tmux I create new terminals

**Comment by francoiscabrol** [comment]
Sorry I have never used fish shell but only zsh. Difficult to say where the error comes from. But the trace print a valid ranger command and if you can open it, it means that ranger itself works. So I guess the error you get is not related to the ranger.vim plugin but to the neovim terminal emulation... not sure

**Comment by duganchen** [comment]
I thought everyone who uses a non-Bourne shell has this in their .vimrc?

    set shell=bash

**Comment by francoiscabrol** [comment]
@Wheele9 does this can fix your issue? ^

**Comment by Wheele9** [comment]
Yes it did! Thanks

**Comment by francoiscabrol** [comment]
Cool. I am going to add something in the README about that
