### ISSUE TITLE
Help understanding this issue

### ISSUE THREAD

**Issue by rmolin88** [francoiscabrol/ranger.vim#46]
Honestly, I am not sure this is an issue with the plugin. The only please I cannot get it to reproduce is inside of vim8. But in neovim the plugin looks like this:
![18-02-21_06 06 51](https://user-images.githubusercontent.com/5428479/36477557-96f9a374-16cf-11e8-8d77-d004f203dd2c.png)

I've tried removing all of ranger configurations, neovim configurations and nothing. Any ideas would be great! 
Thanks for a great plugin!

**Comment by francoiscabrol** [comment]
Ranger, by default, is going to be take the colors of the terminal emulator where it runs. With vim, this plugin is going to run ranger in your terminal emulator (the one where you are running vim). With neovim, it's going to run ranger inside the neovim's terminal emulator. This neovim's terminal emulator should use the vim colorscheme and ranger should use these colors as well. Which colorscheme do you use with neovim?

**Comment by rmolin88** [comment]
Thanks for the response. I think is a terminal issue. I can reproduce with zero configuration on neovim, ranger, and bashrc. What terminal do you use?  I can reproduce by just doing `:term ranger`. I normally use `termite`, I tried `kitty` and got the same results.

**Comment by francoiscabrol** [comment]
I use iterm2... i don’t think it’s your terminal emulator but the neovim’s Terminal emulator. Can you try with a neovim colorscheme?

**Comment by rmolin88** [comment]
Funny story:
I was attempting to make an [asciinema](https://asciinema.org) to show the issue. when I get an error message launching asciinema about `locale`. :boom:! it all made sense. Locale settings in my arch machines were not set properly. Therefore, the issue!.  Setting `LANG=en_US.UTF-8` did it.

Thanks a lot for the help!

**Comment by Zeioth** [comment]
If someone else is experiencing locale issues, it can be fixed adding this to vim config file:

    let g:ranger_command_override = 'LC_ALL=es_ES.UTF8 ranger'

Just use your locale instead of es_ES.UTF8
