### ISSUE TITLE
Can't exit terminal mode after closing ranger (neovim)

### ISSUE THREAD

**Issue by CT075** [francoiscabrol/ranger.vim#47]
Currently, when ranger exits (on file choose, or pressing q), neovim hangs in terminal mode. <C-/><C-N> doesn't work, nor can I get it to return to normal mode at all. After some debugging, it seems that nvim somehow isn't aware that ranger is closed (or at least the rangerCallback.on_exit function is never being run), and I've no idea why. Is this an issue with my configuration? A blank init.vim with just this plugin has the same problem, so I'm totally stumped.

Caveat -- I am running ranger directly via a symlink to the ranger.py script, not from a system install.

**Comment by francoiscabrol** [comment]
can you try to run it from the system install? just to see if it is related... if the on_exit function is not called it is maybe an issue with the neovim terminal

**Comment by CT075** [comment]
It seems to be an [issue](https://github.com/neovim/neovim/issues/8104) with the neovim terminal.

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/issues/8104 was fixed in Nvim 0.3.1 (prerelease).
