### ISSUE TITLE
Bad buffer handling

### ISSUE THREAD

**Issue by casperravenhorst** [francoiscabrol/ranger.vim#48]
When launching vim with `vim .`, selecting two files with space, and then pressing enter to open them (great feature btw), my up arrow keybindings (scroll the view up) is stolen, and it just takes me back to the empty buffer that I guess was temporarily meant for ranger. It has the name of the directory as a file name, and in the status line (the one where the :commands go) it says `"~/blabla/dir" is a directory`. This weirdness does not happen if I open ranger from within vim, let's say for example with a `:RangerCurrentFile` command - so only when `:e`ing a directory. Maybe you know Franco, or maybe I can look into it myself.

PS I'm working from an iTerm2 terminal with tmux on OSX.
edit: just arrow `<up>` key, not down.

**Comment by francoiscabrol** [comment]
I reproduced the issue with neovim but I don't know why this happens :/

**Comment by francoiscabrol** [comment]
yes so it looks like the ranger's buffer is not closed when you open several files at once

**Comment by francoiscabrol** [comment]
it's closed to the issue #45

**Comment by casperravenhorst** [comment]
I will look more into it like the difference between how vim and nvim handle this now

**Comment by casperravenhorst** [comment]
> yes so it looks like the ranger's buffer is not closed when you open several files at once

I think that might be logical, if we open two files we have to `:bp` twice to get to the empty buffer. I'm not versed in vimscript btw, I'm not sure why a buffer is even opened for it.

**Comment by casperravenhorst** [comment]
I just removed a ^k (control-k) keybinding in my .zshrc, and changed lines 108-109 in just `exec "bd 1"`, which seems to have fixed it.

**Comment by casperravenhorst** [comment]
It also messes up filetype detection when opening the multiple files from `vim .`.

**Comment by casperravenhorst** [comment]
At this point of my problem; the problem is actually twofold
* the tabline from vim-airline plugin shows the browser (Ranger) buffer after browsing, even though in `:buffers` it is not even there anymore. So, a simple case of the refresh being called to early
* up and down arrow keys are remapped/stolen by that buffer, so that after exploring these are not usable anymore because they will switch back to the empty explorer buffer! (even when using up/down arrow to scroll through history when in `:command` mode)

Somehow, *the first is fixed* by removing vim-autoclose (don't have the option to git pull it right now to see if it is fixed), and *the second* by removing vim-unimpaired (idem). I use pathogen for plugin mgmt. How about you? Do you have the same plugin set and plugin manager?

**Comment by francoiscabrol** [comment]
I don't use these two plugins... finally I think your issue was not the same as me because I did some tests and I realized that it works for me with `vim .` but not with `e .` which is an other story not related. If you have fixed the problem and found an incompatibility with these plugins, it will be added in the readme. 
And as plugin manager I use vim-plug which one I recommend :)

**Comment by casperravenhorst** [comment]
Yeah if I really have a patch for this that makes it better for all users, I'll submit a MR. For now you can close it! Thanks.

**Comment by Migacz85** [comment]
@casperravenhorst Hi, can you post his patch ? :-) I'm experiencing simillar problems with buffers and ranger.
