### ISSUE TITLE
Small delay on file opening

### ISSUE THREAD

**Issue by michelesr** [francoiscabrol/ranger.vim#51]
I've noticed that it takes about 1-2 seconds from the moment you select a file in ranger and press `<CR>` to the moment when vim actually opens that file.

I'm running Neovim and I tried also running it without any plugin (`nvim -u NONE`) and sourcing ranger plugin manually (`:so ranger.vim`) but I still get the same behavior.

I get no delay when opening files using `:edit` or other methods (such as other plugins to find and open files).

Is that normal?

If not, have you got any suggestion to fix this problem?

**Comment by francoiscabrol** [comment]
I use neovim and I don't have any delay... it takes few ms to open but not seconds. Sorry I didn't see your issue before. Can you try to open ranger directly in the terminal and see if you have the same delay?

**Comment by michelesr** [comment]
I have no delay when using ranger standalone:

[![asciicast](https://asciinema.org/a/0fDTJAzKLSMvyABmrCxjOvsJk.png)](https://asciinema.org/a/0fDTJAzKLSMvyABmrCxjOvsJk)
