### ISSUE TITLE
Too many arguments for function: OpenRangerIn

### ISSUE THREAD

**Issue by jorgeegomez** [francoiscabrol/ranger.vim#53]
On a clean install of Ubuntu 18.04 (vim version 8.0), I'm getting
`E118: Too many arguments for function: OpenRangerIn`
When trying to run :Ranger or <leader>f

ranger.vim is the only plugin installed, after vim-plug.

**Comment by francoiscabrol** [comment]
yes it's going to be fix by #52

**Comment by francoiscabrol** [comment]
it should be fix now!
