### ISSUE TITLE
Make the ranger key mapping customizable

### ISSUE THREAD

**Issue by marcaddeo** [francoiscabrol/ranger.vim#6]
I use `<leader>f` already for another binding, would make sense to have a customizable mapping here instead of "hijacking" it globally.

**Comment by francoiscabrol** [comment]
Yes it would make sense... but I don't want to introduce a breaking change for the people who use it already. We could maybe add a condition: if the mapping exists already so do nothing and let the user set an other mapping in his config file... What do you suggest?

**Comment by marcaddeo** [comment]
Why not just set what you currently have as the default, but allow the option to change it.

**Comment by francoiscabrol** [comment]
But you can already set your own mapping by adding this in your vimrc: map yourkeys :call OpenRanger()<CR>

**Comment by francoiscabrol** [comment]
is it not what you expect?

**Comment by rosshadden** [comment]
Shipping with mappings is a vim anti-pattern.  Those of us with things already mapped to the keys you use can no longer use our old mappings.  It would be best and easiest to simply remove the mapping line entirely, and tell users to map it in the readme.  This is a well-accepted, well-mannered pattern.

**Comment by francoiscabrol** [comment]
but it seems that the most of vim's plugin provide default keys bindings, you don't think so?

**Comment by rosshadden** [comment]
If plugins provide their own mappings, they also usually provide an option to disable all default mappings.

You of course don't have to do anything, it's just a personal project :smile: We're all just offering it as a suggestion.  Also any one of us could easily change it ourselves and submit a pull request.  This issue kind of just serves as a placeholder for one of us getting motivated enough to do so.

**Comment by francoiscabrol** [comment]
I found a good documentation that provide solutions for the key mapping: http://stevelosh.com/blog/2011/09/writing-vim-plugins/#mapping-keys-the-right-way. Iam going to add the option to disable the default mapping.
