### ISSUE TITLE
Neovim-like incsearch

### ISSUE THREAD

**Issue by whitebyte** [francoiscabrol/ranger.vim#66]
Hi, is it possible to enable Neovim-like search (incsearch) in Ranger? Basically It's a "search as you type", so the cursor automatically jumps to the best match while searching. Or, even better, maybe there is a way to make Ranger respect Vim seach options (incsearch, smartcase etc)?

**Comment by francoiscabrol** [comment]
^ Does it answer you question?

**Comment by whitebyte** [comment]
Sorry, it seems that I failed to explain correctly what I want. I'm not speaking about fuzzy search. What I want is to make Ranger jump to the first suitable serch result *without* waiting for `Enter` keypress, just like Neovim search with `incsearch` enabled.

**Comment by francoiscabrol** [comment]
Ok I see. In the ranger documentation they are talking about the command `search_inc pattern` which one I tried and it's doing what you want! after that I guess you just have to set a shortcut in the ranger's config for this `search_inc` command.

**Comment by whitebyte** [comment]
Yeah, thanks
