### ISSUE TITLE
RangerCurrentFileNewTab: possible to open in existing window (when existant)?

### ISSUE THREAD

**Issue by divramod** [francoiscabrol/ranger.vim#78]
Hey, thx for the awesome plugin!
It really gave me a boost.

I am mostly using RangerCurrentFileNewTab as trigger.
Sometimes it happens, that the new file i am opening is already open in another tab.
The current behavior of RangerCurrentFileNewTab is, that it opens a new tab despite the fact, that the file is already open, so that i have two tabs for the same file. 

I would prefer to let RangerCurrentFileNewTab trigger a jump to the already open tab.
Is that somehow possible with the current state of the plugin?

thx again!

**Comment by francoiscabrol** [comment]
It is technically possible but could be outside the scope of this plugin. Maybe the solution is to use an other vim plugin for this purpose. A plugin that would force vim to focus on the related window in the case the file is already opened.

**Comment by francoiscabrol** [comment]
or maybe we could use this `drop` command I have just found https://vim.fandom.com/wiki/Edit_a_file_or_jump_to_it_if_already_open

**Comment by divramod** [comment]
i opened a pull request for that one with the drop idea https://github.com/francoiscabrol/ranger.vim/pull/83
