### ISSUE TITLE
small  fix

### ISSUE THREAD

**Issue by sharethewisdom** [francoiscabrol/ranger.vim#8]
hi, could you add the bang attribute to the command definition at the following line please? vim is complaining when I update.
https://github.com/francoiscabrol/ranger.vim/blob/master/plugin/ranger.vim#L66

thanks!

**Comment by francoiscabrol** [comment]
Something like that? 
command! -bang Ranger call OpenRanger()

**Comment by sharethewisdom** [comment]
No, just `command! Ranger call OpenRanger()`, so that the Ranger command will be overwritten when updating without error message.

**Comment by francoiscabrol** [comment]
oh ok thanks iam going to do the change!
