### ISSUE TITLE
conflict with "indentLine"

### ISSUE THREAD

**Issue by z-huabao** [francoiscabrol/ranger.vim#80]
I use [Yggdroot/indentLine](https://github.com/Yggdroot/indentLine)

```
Plug 'Yggdroot/indentLine'
let g:indentLine_char='┆' 
let g:indentLine_enabled = 1
```
so `ranger.vim` show '┆'  in indent blank.

![2019-08-20 13-46-34 的屏幕截图](https://user-images.githubusercontent.com/27676436/63321278-d16fa400-c352-11e9-9fbd-66e938745944.png)

**Comment by z-huabao** [comment]
check filetype and diable indentLine solve it

**Comment by rokr-dev** [comment]
For Neovim
```
autocmd TermEnter * IndentLinesDisable
```
