### ISSUE TITLE
Image preview in neovim

### ISSUE THREAD

**Issue by ChristianChiarulli** [francoiscabrol/ranger.vim#95]
Do you have an suggestions to achieve image preview in neovim?

**Comment by ChristianChiarulli** [comment]
I'm using ueberzug on linux, not working on mac so closing I guess

**Comment by alfredhua** [comment]
hello，how to solve this question?

**Comment by shendypratamaa** [comment]
@ChristianChiarulli after research how to fix this, btw i'm using iterm2 on mac os monterey 12.0.1, for the first i cant see image preview using ranger after installing, when im try to hover it no preview available, and then i change ur code on ur blog pos at line 1 where u recomended using set preview_images_method ueberzug, to iterm2, and work 💯

**Comment by shendypratamaa** [comment]
@ChristianChiarulli after research how to fix this, btw i'm using iterm2 on mac os monterey 12.0.1, for the first i cant see image preview using ranger after installing, when i'm try to hover it no preview available, and then i change ur code on ur blog https://www.chrisatmachine.com/Neovim/07-ranger/ pos at line 1 where u recomended using set preview_images_method ueberzug, i change to iterm2, and it's work 💯 

if someone have some issue like me u can try that @alfredhua,
but i have 1 more issue, if i'm open ranger inside tmux, preview not available again 😅 🤯

<img width="1022" alt="Screenshot 2021-12-11 at 15 04 59" src="https://user-images.githubusercontent.com/76093597/145669367-d63d5577-1212-4c3e-b234-ec3da00ee8ff.png">
